/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.conversor;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class conversorTemperatura extends javax.swing.JFrame {

    /**
     * Creates new form conversorTemperatura
     */
    public conversorTemperatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_BienvenidaTemp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboBoxEleccionTemp = new javax.swing.JComboBox<>();
        txtFieldTemp = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        btnCancelarT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_BienvenidaTemp.setText("Conversor Temperaturas");

        jLabel1.setText("Bienvenido al conversor de Temperatura");

        comboBoxEleccionTemp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centigrados a Kelvin", "Centigrados a Farenheit", "Kelvin a Centigrados", "Kelvin a Farenheit", "Farenheit a Centigrados", "Farenheit a Kelvin" }));

        txtFieldTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldTempActionPerformed(evt);
            }
        });
        txtFieldTemp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldTempKeyTyped(evt);
            }
        });

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        btnCancelarT.setText("Cancelar");
        btnCancelarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnConvertir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarT)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lbl_BienvenidaTemp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(comboBoxEleccionTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtFieldTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_BienvenidaTemp)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(comboBoxEleccionTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(txtFieldTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConvertir)
                    .addComponent(btnCancelarT))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldTempActionPerformed

    private void btnCancelarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTActionPerformed
        menuPrincipal menu = new menuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarTActionPerformed

    private void txtFieldTempKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldTempKeyTyped
        char c = evt.getKeyChar();
        if(c < '0' || c > '9') evt.consume();        
    }//GEN-LAST:event_txtFieldTempKeyTyped

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
    String eleccion = (String)comboBoxEleccionTemp.getSelectedItem();
    String texto = txtFieldTemp.getText();
    double valor = 0.0;
    try{
        valor = Double.parseDouble(texto);
    }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor numérico válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    conversionTemperatura nConversion = new conversionTemperatura();
    switch(eleccion) {
        case "Centigrados a Kelvin":
            JOptionPane.showMessageDialog(null,nConversion.celsiusToKelvin(valor) + "Kelvins");
            break;
        case "Centigrados a Farenheit":
            JOptionPane.showMessageDialog(null,nConversion.celsiusToFarenheit(valor) + "Farenheits");
            break;
        case "Kelvin a Centigrados":
            JOptionPane.showMessageDialog(null,nConversion.kelvinToCelsius(valor) + "Centigrados");
            break;
        case "Kelvin a Farenheit":
            JOptionPane.showMessageDialog(null,nConversion.kelvinToFarenheit(valor) + "Farenheits");
            break;   
        case "Farenheit a Centigrados":
            JOptionPane.showMessageDialog(null,nConversion.farenheitToCelsius(valor) + "Centigrados");
            break; 
        case "Farenheit a Kelvin":
            JOptionPane.showMessageDialog(null,nConversion.farenheitToKelvin(valor) + "Kelvin");
            break; 
            
    }
        int eleccionCuadro = JOptionPane.showConfirmDialog(null, "¿Desea Continuar?",
                "Select an Option", JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE);              

        switch (eleccionCuadro) {
            case JOptionPane.YES_OPTION:
                menuPrincipal menuNuevo = new menuPrincipal();
                dispose();
                menuNuevo.setVisible(true);
                break;
            case JOptionPane.NO_OPTION:
                JOptionPane.showMessageDialog(rootPane, "Programa Finalizado");
                System.exit(0);
                break;
            case JOptionPane.CANCEL_OPTION:
                JOptionPane.showMessageDialog(rootPane, "Programa Finalizado");
                System.exit(0);
                break;
            
        }            
        
    
    }//GEN-LAST:event_btnConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conversorTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conversorTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conversorTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conversorTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conversorTemperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarT;
    private javax.swing.JButton btnConvertir;
    private javax.swing.JComboBox<String> comboBoxEleccionTemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_BienvenidaTemp;
    private javax.swing.JTextField txtFieldTemp;
    // End of variables declaration//GEN-END:variables
}
